### ISSUE TITLE
Permission denied for servers.json

### ISSUE THREAD

**Issue by cryptochrome** [Dahlgren/docker-arma-server-web-admin#2]
Hi,

I installed the docker container but when I try to do anything in the web UI, I am getting a bunch of permission errors. When trying to access the logs, the API call is getting a 500 error and when I try to add a server, I get this:

```
[Error: EACCES: permission denied, open 'servers.json'] {                                                                                                                         
  errno: -13,                                                                                                                                                                     
  code: 'EACCES',                                                                                                                                                                 
  syscall: 'open',                                                                                                                                                                
  path: 'servers.json'                                                                                                                                                            
}                                    
```

**Comment by Dahlgren** [comment]
You can use `ls -n` to see user and group owner of your server directory files, specifically the servers.json but it should match the rest of the files. These ids should be used as PUID and GUID environment variables so that the manager runs with permissions to your arma 3 server files. The example script will use the same user as the one that starts the container.

Arma 3 server requires read and write permissions to any addon folders that are to be used so ideally the entire arma 3 server directory and all mods should be owner by one user/group that is also used for the manager.

**Comment by cryptochrome** [comment]
The permissions were alright. I stopped investigating further though and moved to a normal, non-container installation. Where it works like a champ. Thank you! 👍
