### ISSUE TITLE
Doesn't read or write servers.json

### ISSUE THREAD

**Issue by VulturARG** [Dahlgren/docker-arma-server-web-admin#3]
I have problems similar to those described at [#2](https://github.com/Dahlgren/docker-arma-server-web-admin/issues/2)

The program never reads or writes the servers.json file.

Tests performed:
- Give permissions with chmod 777 to all / app files from the container
- Testing with and without the servers.json file
- Use a servers.json file brought from a non-docker version

In all cases when launching the program it always looked the same and never recorded any data because it said that it did not have permissions

**Comment by Dahlgren** [comment]
What volumes are mounted to the container and which user is used to run the application in the container?

**Comment by VulturARG** [comment]
I use this docker-composer.yml to run it

`version: "3.1"

services:
  arga-web-panel:
    image: dahlgren/arma-server-web-admin
    container_name: arga-web-panel
    restart: always
    ports:
      - 3300:3000
    volumes:
      - /home/steam/steamcmd/arma3:/arma3
    environment:
      - PUID=1002
      - GUID=1002
    extra_hosts:
      - "argahost:xxx.xxx.xxx.xxx" #My IP`

**Comment by Coronelcortez** [comment]
Hi!
I'm having the same issues, is there a fix?
![image_2021-06-22_20-06-57](https://user-images.githubusercontent.com/4683315/123011476-d78f9b00-d396-11eb-98d7-59f422bf6746.png)

I tried using a diferent user and group id (with higher privileges) but nothing.
Each time I create a server, the container restarts.

This is my docker-compose

version: "3.3"

services:
 arma-web-panel:
  image: dahlgren/arma-server-web-admin
  container_name: arma-web-panel
  restart: always
  ports:
  - "3000:3000"
  volumes:
  - /home/arma/.steam/steamcmd/arma3:/arma3
  environment:
  - GAME_PATH="/arma3"
  - GAME_TYPE="arma3"
  - PUID="1000"
  - GUID="1000"
  - USERNAME=admin
  - PASSWORD=temp

Thank you very much!
PS: Luis, si le encontraste una solucion, te super agradeceria si me contas como hiciste, saludos desde Random Operators, de Bariloche!

**Comment by Dahlgren** [comment]
@Coronelcortez does uid/gid 1000:1000 have write access to `/home/arma/.steam/steamcmd/arma3`?

**Comment by VulturARG** [comment]
@Coronelcortez: no solution yet. I was waiting the anwser of @Dahlgren 
PS: No seguí investigando. Estamos cerca. Yo estoy en Roca.

**Comment by Coronelcortez** [comment]
> @Coronelcortez does uid/gid 1000:1000 have write access to `/home/arma/.steam/steamcmd/arma3`?

Yes, it has write access. Currently i'm using 1001, the owner of the files. 
I managed to get the container up and running, now the previously cited error only ocurrs referring to a battleye folder, but that seems to be a minor issue.
Now the web admin works, I can list, create and erase servers without causing the container to reboot. 
Buuuuuut, because there is always a "but", now I cant start the servers.
The next lines refer to the creation of a server and the failed start action (it doesnt says more than that)

EDIT: checking de logs from the web panel, I see that the only error registered is this one:

`15:05:22 SteamAPI initialization failed. Steam features won't be accessible!
`
```
arma-web-panel    | POST /api/servers/ 200 1.302 ms - 386
arma-web-panel    | GET /api/servers/ 200 1.925 ms - 388
arma-web-panel    | POST /api/servers/Test2/start 200 31.779 ms - 24
arma-web-panel    | POST /api/servers/Test2/start 200 25.900 ms - 24
arma-web-panel    | POST /api/servers/Test2/start 200 21.538 ms - 24
arma-web-panel    | POST /api/servers/Test2/start 200 21.007 ms - 24
```

Any clue on what could it be?
Thank you again!

Luis, no se si estamos/estabamos teniendo exactamente el mismo problema, pero por las dudas acá va lo que hice.
Basicamente me asegure que todo el contenido del directorio de instalación del ARMA3 perteneciese, ui y gid, al usuario "arma" (que es el que yo uso en el server), y esos mismos ID son los que especifique en la script.

Como tuve que meter mano por todos lados, forkee el repo del web server, y usando el dockerfile que hay aca de guia, me arme mi propia imagen de docker, y la corro con docker-compose. Te dejo ambos archivos aca.

```
version: "3.3"
services:

  arma-web-panel:
    container_name: arma-web-panel
    build:
      context: /home/ubuntu/docker-arma-server-web-admin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /home/arma/.steam/steamcmd/arma3:/arma3:rw
```

y acá el Dockerfile con el que construye la imagen, fijate que cambié la url de donde toma el web-server (por comodidad propia para futuros cambios) y le agregue esta seccion, donde defino las variables que va a usar la script start.sh.

```
#Define environment variables
ENV GAME_TYPE="arma3"
ENV GAME_PATH="/arma3"
ENV USERNAME="admin"
ENV PASSWORD="admin123"
```

```
FROM node:12-buster

# Install git
RUN apt-get update && apt-get install -y git lib32stdc++6 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create application folder
RUN mkdir /app

# Create application user
RUN useradd -u 1001 -U -s /bin/false arma && usermod -G users arma

# Download Arma Server Web Manager
RUN git clone https://github.com/Coronelcortez/arma-server-web-admin.git /app

# Install node dependencies for the application
WORKDIR /app
RUN npm install

# Copy start application script
COPY start.sh /app/

#Define environment variables
ENV GAME_TYPE="arma3"
ENV GAME_PATH="/arma3"
ENV USERNAME="admin"
ENV PASSWORD="admin123"

# Start application
CMD ./start.sh

# Declare application port
EXPOSE 3000
```

**Comment by VulturARG** [comment]
Thanks @Coronelcortez. I'll try

**Comment by Dahlgren** [comment]
@Coronelcortez Sometimes steam does not correctly set the executable flag on the arma3server and/or arma3server_x64 binary, make sure it's executable with `chmod +x arma3server`

**Comment by Coronelcortez** [comment]
> @Coronelcortez Sometimes steam does not correctly set the executable flag on the arma3server and/or arma3server_x64 binary, make sure it's executable with `chmod +x arma3server`

Yep, both files have execution flags.

![consola](https://user-images.githubusercontent.com/4683315/123336330-18fd8300-d51c-11eb-8d4d-ea94747a11a3.png)

**Comment by Diyagi** [comment]
Found the issue, the arma server tries to write files in the user home folder, but there is no user home folder.

**Comment by Dahlgren** [comment]
Should be fixed by https://github.com/Dahlgren/docker-arma-server-web-admin/commit/8cf81eb4fe2a5ae01cc5139b4d11c23eab29270e
